//
//  CountryHelper.swift
//  jajko
//
//  Created by Esteban Garro on 2015-06-19.
//  Copyright (c) 2015 transcriptics. All rights reserved.
//

import Foundation

let countries = [
    "af" : "Afghanistan",
    "al" : "Albania",
    "dz" : "Algeria",
    "as" : "American",
    "ad" : "Andorra",
    "ao" : "Angola",
    "ai" : "Anguilla",
    "aq" : "Antarctica",
    "ag" : "Antigua",
    "ar" : "Argentina",
    "am" : "Armenia",
    "aw" : "Aruba",
    "au" : "Australia",
    "at" : "Austria",
    "az" : "Azerbaijan",
    "bs" : "Bahamas",
    "bh" : "Bahrain",
    "bd" : "Bangladesh",
    "bb" : "Barbados",
    "by" : "Belarus",
    "be" : "Belgium",
    "bz" : "Belize",
    "bj" : "Benin",
    "bm" : "Bermuda",
    "bt" : "Bhutan",
    "bo" : "Bolivia",
    "ba" : "Bosnia",
    "bw" : "Botswana",
    "bv" : "Bouvet Island",
    "br" : "Brazil",
    "io" : "British Indian Ocean Territory",
    "vg" : "British Virgin Islands",
    "bn" : "Brunei",
    "bg" : "Bulgaria",
    "bf" : "Burkina Faso",
    "bi" : "Burundi",
    "kh" : "Cambodia",
    "cm" : "Cameroon",
    "ca" : "Canada",
    "cv" : "Cape Verde",
    "ky" : "Cayman Islands",
    "cf" : "Central African Republic",
    "td" : "Chad",
    "cl" : "Chile",
    "cn" : "China",
    "cx" : "Christmas Island",
    "cc" : "Cocos Islands",
    "co" : "Colombia",
    "km" : "Comoros",
    "cd" : "Congo, Democratic Republic of",
    "cg" : "Congo, People's Republic of",
    "ck" : "Cook Islands",
    "cr" : "Costa Rica",
    "ci" : "Cote D'Ivoire",
    "cu" : "Cuba",
    "cy" : "Cyprus",
    "cz" : "Czech Republic",
    "dk" : "Denmark",
    "dj" : "Djibouti",
    "dm" : "Dominica",
    "do" : "Dominican Republic",
    "ec" : "Ecuador",
    "eg" : "Egypt",
    "sv" : "El Salvador",
    "gq" : "Equatorial Guinea",
    "er" : "Eritrea",
    "ee" : "Estonia",
    "et" : "Ethiopia",
    "fo" : "Faeroe Islands",
    "fk" : "Falkland Islands",
    "fj" : "Fiji",
    "fi" : "Finland",
    "fr" : "France",
    "gf" : "French Guiana",
    "pf" : "French Polynesia",
    "tf" : "French Southern Territories",
    "ga" : "Gabon",
    "gm" : "Gambia",
    "ge" : "Georgia",
    "de" : "Germany",
    "gh" : "Ghana",
    "gi" : "Gibraltar",
    "gr" : "Greece",
    "gl" : "Greenland",
    "gd" : "Grenada",
    "gp" : "Guadaloupe",
    "gu" : "Guam",
    "gt" : "Guatemala",
    "gn" : "Guinea",
    "gw" : "Guinea-Bissau",
    "gy" : "Guyana",
    "ht" : "Haiti",
    "hm" : "Heard and McDonald Islands",
    "va" : "Holy See (Vatican City State)",
    "hn" : "Honduras",
    "hk" : "Hong Kong",
    "hr" : "Hrvatska",
    "hu" : "Hungary",
    "is" : "Iceland",
    "in" : "India",
    "id" : "Indonesia",
    "ir" : "Iran",
    "iq" : "Iraq",
    "ie" : "Ireland",
    "il" : "Israel",
    "it" : "Italy",
    "jm" : "Jamaica",
    "jp" : "Japan",
    "jo" : "Jordan",
    "kz" : "Kazakhstan",
    "ke" : "Kenya",
    "ki" : "Kiribati",
    "kp" : "Korea, Democratic People's Republic of",
    "kr" : "Korea, Republic of",
    "kw" : "Kuwait",
    "kg" : "Kyrgyz Republic",
    "la" : "Lao People's Democratic Republic",
    "lv" : "Latvia",
    "lb" : "Lebanon",
    "ls" : "Lesotho",
    "lr" : "Liberia",
    "ly" : "Libyan Arab Jamahiriya",
    "li" : "Liechtenstein",
    "lt" : "Lithuania",
    "lu" : "Luxembourg",
    "mo" : "Macao",
    "mk" : "Macedonia",
    "mg" : "Madagascar",
    "mw" : "Malawi",
    "my" : "Malaysia",
    "mv" : "Maldives",
    "ml" : "Mali",
    "mt" : "Malta",
    "mh" : "Marshall Islands",
    "mq" : "Martinique",
    "mr" : "Mauritania",
    "mu" : "Mauritius",
    "yt" : "Mayotte",
    "mx" : "Mexico",
    "fm" : "Micronesia",
    "md" : "Moldova",
    "mc" : "Monaco",
    "mn" : "Mongolia",
    "ms" : "Montserrat",
    "ma" : "Morocco",
    "mz" : "Mozambique",
    "mm" : "Myanmar",
    "na" : "Namibia",
    "nr" : "Nauru",
    "np" : "Nepal",
    "an" : "Netherlands Antilles",
    "nl" : "Netherlands",
    "nc" : "New Caledonia",
    "nz" : "New Zealand",
    "ni" : "Nicaragua",
    "ne" : "Niger",
    "ng" : "Nigeria",
    "nu" : "Niue",
    "nf" : "Norfolk Island",
    "mp" : "Northern Mariana Islands",
    "no" : "Norway",
    "om" : "Oman",
    "pk" : "Pakistan",
    "pw" : "Palau",
    "ps" : "Palestinian Territory",
    "pa" : "Panama",
    "pg" : "Papua New Guinea",
    "py" : "Paraguay",
    "pe" : "Peru",
    "ph" : "Philippines",
    "pn" : "Pitcairn Island",
    "pl" : "Poland",
    "pt" : "Portugal",
    "pr" : "Puerto Rico",
    "qa" : "Qatar",
    "re" : "Reunion",
    "ro" : "Romania",
    "ru" : "Russian Federation",
    "rw" : "Rwanda",
    "sh" : "St. Helena",
    "kn" : "St. Kitts and Nevis",
    "lc" : "St. Lucia",
    "pm" : "St. Pierre and Miquelon",
    "vc" : "St. Vincent and the Grenadines",
    "ws" : "Samoa",
    "sm" : "San Marino",
    "st" : "Sao Tome and Principe",
    "sa" : "Saudi Arabia",
    "sn" : "Senegal",
    "cs" : "Serbia and Montenegro",
    "sc" : "Seychelles",
    "sl" : "Sierra Leone",
    "sg" : "Singapore",
    "sk" : "Slovakia",
    "si" : "Slovenia",
    "sb" : "Solomon Islands",
    "so" : "Somalia",
    "za" : "South Africa",
    "gs" : "South Georgia and the South Sandwich Islands",
    "es" : "Spain",
    "lk" : "Sri Lanka",
    "sd" : "Sudan",
    "sr" : "Suriname",
    "sj" : "Svalbard & Jan Mayen Islands",
    "sz" : "Swaziland",
    "se" : "Sweden",
    "ch" : "Switzerland",
    "sy" : "Syrian Arab Republic",
    "tw" : "Taiwan",
    "tj" : "Tajikistan",
    "tz" : "Tanzania",
    "th" : "Thailand",
    "tl" : "Timor-Leste",
    "tg" : "Togo",
    "tk" : "Tokelau",
    "to" : "Tonga",
    "tt" : "Trinidad and Tobago",
    "tn" : "Tunisia",
    "tr" : "Turkey",
    "tm" : "Turkmenistan",
    "tc" : "Turks and Caicos Islands",
    "tv" : "Tuvalu",
    "vi" : "US Virgin Islands",
    "ug" : "Uganda",
    "ua" : "Ukraine",
    "ae" : "United Arab Emirates",
    "gb" : "United Kingdom",
    "um" : "United States Minor Outlying Islands",
    "us" : "United States of America",
    "uy" : "Uruguay",
    "uz" : "Uzbekistan",
    "vu" : "Vanuatu",
    "ve" : "Venezuela",
    "vn" : "Viet Nam",
    "wf" : "Wallis and Futuna Islands",
    "eh" : "Western Sahara",
    "ye" : "Yemen",
    "zm" : "Zambia",
    "zw" : "Zimbabwe"
]

class CountryHelper : NSObject {
    
    class func allCountries() -> [String] {
        return (countries as NSDictionary).allValues.map({ $0 as! String })
    }
    
    class func countryStringFor(code: String) -> String? {
        return countries[code]
    }
    
    class func languageCodeFor(language: String) -> String? {
        var found = false
        var resp:String? = nil
        for (key, value) in countries {
            if language.lowercaseString == value.lowercaseString {
                resp = key
                found = true
                break
            }
        }
        
        if found {
            return resp
        }
        
        //Try a softer match:
        for (key, value) in countries {
            if value.lowercaseString.rangeOfString(language.lowercaseString) != nil {
                return key
            }
        }
        
        return nil
    }
}